spring.application.name=music

uploadcare.public-key=3914c16e6746654a1e29
uploadcare.secret-key=6b6c33f9ee181a5c2264

jwt.secret=25f8318239821bc836294dfa9bb9922e651cd296500cdf92a287bb090ade2b8c
jwt.expiration=86400000

spring.r2dbc.url=r2dbc:postgresql://spotify-music-db.ctum4e4coks5.eu-north-1.rds.amazonaws.com:5432/postgres?sslMode=require
spring.r2dbc.username=postgres
spring.r2dbc.password=Aale#1234
#
#spring.r2dbc.url=r2dbc:postgresql://localhost:5432/MusicDb
#spring.r2dbc.username=postgres
#spring.r2dbc.password=Prakash@123

spring.r2dbc.pool.enabled=true
spring.r2dbc.pool.initial-size=5
spring.r2dbc.pool.max-size=20
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql